//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int Id_comentario { get; set; }
        public string Comentario1 { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_post { get; set; }
        public Nullable<int> Id_usuario { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
