//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int Id_like { get; set; }
        public int Id_post { get; set; }
        public int Id_usuario { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
