//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comentario = new HashSet<Comentario>();
            this.Like = new HashSet<Like>();
        }
    
        public int Id_post { get; set; }
        public string Mensaje { get; set; }
        public string Archivo_mp3 { get; set; }
        public System.DateTime Fecha_creacion { get; set; }
        public Nullable<int> Id_usuario { get; set; }
        public Nullable<int> Id_agrupacion { get; set; }
    
        public virtual Agrupacion Agrupacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Like { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
