//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int Id_usuario { get; set; }
        public int Id_agrupacion { get; set; }
        public string Estatus { get; set; }
    
        public virtual Agrupacion Agrupacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
